import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import TanstackQueryProvider from '@/providers/tanstack-query.provider'
import './globals.css'

const fontSans = Inter({
  subsets: ['vietnamese']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={`${fontSans.className} antialiased`}>
        <TanstackQueryProvider>{children}</TanstackQueryProvider>
      </body>
    </html>
  )
}
