import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NextTopLoader from 'nextjs-toploader'

import { Toaster } from '@/components/ui/sonner'
import AppProvider from '@/providers/app.provider'
import TanstackQueryProvider from '@/providers/tanstack-query.provider'
import ThemeProvider from '@/providers/theme.provider'
import './globals.css'

const fontSans = Inter({
  subsets: ['vietnamese']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${fontSans.className} antialiased`}>
        <TanstackQueryProvider>
          <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
            <AppProvider>
              {children}
              <Toaster richColors position='bottom-center' />
              <NextTopLoader showSpinner={false} shadow={false} />
            </AppProvider>
          </ThemeProvider>
        </TanstackQueryProvider>
      </body>
    </html>
  )
}
